### ISSUE TITLE
Please add license information to allow reuse

### ISSUE THREAD

**Issue by a13ph** [noctuid/evil-guide#1]
Great guide already, and hopefully will be even better
[Spacemacs](https://github.com/syl20bnr/spacemacs) can benefit from some if not all parts of it
So, if you are in favor - please add compatible license

And given chance, I want to say - you are _keytastical_

**Comment by noctuid** [comment]
I added a license since I'm fine with anyone doing anything with this. That said, I don't see what's wrong with just linking here. I think it would be preferable not to fragment/fork this while I'm still maintaining it.
