### ISSUE TITLE
Just set evil-want-integration to nil doesn't prevent it set keybindings in dired mode.

### ISSUE THREAD

**Issue by AmaiKinono** [noctuid/evil-guide#15]
Hi. I've read in the guide that:

> In `evil-integration.el`, `evil-make-overriding-map` is used for dired and ibuffer. If you want to prevent `evil-integration.el` from being loaded, you can set `evil-want-integration` to nil *before* loading evil.

I have `SPC` as my prefix key in normal state. But having `evil-want-integration` set to nil, `SPC` still calls `dired-next-line`. It turns out that `evil-integration` doesn't make the overriding map, but `evil-keybindings` does. You have to set `evil-want-keybinding` to nil to prevent that.

I am not so familiar with evil, so I think it's best for you to add some information about this. But I would be happy to (try to) create a PR if you like that.

**Comment by AmaiKinono** [comment]
Actually I found `evil-integration` doesn't make any overriding map, and it's pretty useful. For example, it makes `.` doesn't break some things. Here's what happened when I press `M-x C-g .` with `evil-want-integration` set to nil:

![Peek 2019-04-27 02-18](https://user-images.githubusercontent.com/28714352/56828006-eea7d080-6892-11e9-9fab-8d894437e9e0.gif)

It splits the frame, and my modeline is ruined. But with `evil-integration`, it actually knows I didn't do anything so that won't happen.

**Comment by noctuid** [comment]
Yes there were some changes in evil, and I never updated the guide. I'll fix this.
