### ISSUE TITLE
Leader key part of evil since (at least) 1.14.0, Mar 04, 2020

### ISSUE THREAD

**Issue by kapilhp** [noctuid/evil-guide#16]
Checked with the Info documentation for 'evil' with the above number. Under the section on "Keymaps" there is a section called "Leader Keys". This seems to say that the evil supports vim 'leader' keys. On the other hand the 'evil-guide' says there is no exact analogue of vim's 'leader' keys.

Seems to be some discrepancy. Does one need to install 'evil-leader' or not?

**Comment by noctuid** [comment]
Iirc I was involved in the discussion before it was added. It's still not quite equivalent but should be mentioned in the guide. `evil-leader` is something else entirely.
